// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// thetafun
NumericVector thetafun(NumericVector t, NumericVector y, int gfun, double lambda);
RcppExport SEXP L1splines_thetafun(SEXP tSEXP, SEXP ySEXP, SEXP gfunSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type gfun(gfunSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(thetafun(t, y, gfun, lambda));
    return __result;
END_RCPP
}
// outerG
NumericMatrix outerG(NumericVector t, NumericVector tp, int gfun, bool inv);
RcppExport SEXP L1splines_outerG(SEXP tSEXP, SEXP tpSEXP, SEXP gfunSEXP, SEXP invSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< int >::type gfun(gfunSEXP);
    Rcpp::traits::input_parameter< bool >::type inv(invSEXP);
    __result = Rcpp::wrap(outerG(t, tp, gfun, inv));
    return __result;
END_RCPP
}
// thetafunG
NumericMatrix thetafunG(NumericVector t, NumericVector y, int gfun, double lambda);
RcppExport SEXP L1splines_thetafunG(SEXP tSEXP, SEXP ySEXP, SEXP gfunSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type gfun(gfunSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(thetafunG(t, y, gfun, lambda));
    return __result;
END_RCPP
}
