// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// plusfun
double plusfun(double x);
RcppExport SEXP L1splines_plusfun(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    __result = Rcpp::wrap(plusfun(x));
    return __result;
END_RCPP
}
// G1
double G1(double s, double t);
RcppExport SEXP L1splines_G1(SEXP sSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    __result = Rcpp::wrap(G1(s, t));
    return __result;
END_RCPP
}
// outerfun
NumericMatrix outerfun(NumericVector t, NumericVector y, int gfun, double lambda);
RcppExport SEXP L1splines_outerfun(SEXP tSEXP, SEXP ySEXP, SEXP gfunSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type gfun(gfunSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    __result = Rcpp::wrap(outerfun(t, y, gfun, lambda));
    return __result;
END_RCPP
}
