# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

plusfun <- function(x) {
    .Call('L1splines_plusfun', PACKAGE = 'L1splines', x)
}

G1 <- function(s, t) {
    .Call('L1splines_G1', PACKAGE = 'L1splines', s, t)
}

#' something something
#'
#' @description
#' @param x A matrix.
#' @return A matrix of same size as x.
#' @author Helene Charlotte Rytgaard
#' @examples
#' @export
outerfun <- function(t, y, gfun, lambda) {
    .Call('L1splines_outerfun', PACKAGE = 'L1splines', t, y, gfun, lambda)
}

